apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-ingress.fullname" . }}
  labels:
    {{- include "nginx-ingress.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "nginx-ingress.selectorLabels" . | nindent 4 }}
